baseURL: https://moqu.me/
languageCode: en-gb
title: Moqume
theme: PaperMod
pagination:
  paperSize: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

caches:
  images:
    dir: :cacheDir/images
